# -------------------------------------------------------------------------------------
# Author Configuration | 作者配置
# -------------------------------------------------------------------------------------

name = "剑胆琴心"
email = "xuepengshuai@gmail.com"
link = "http://shuai06.github.io"